Repository THD-AI-2023/Devablos-Project, pull requests merged in 2024-05, with the labels that each got.

#1 Chore: Project Setup
  .github/dependabot.yml
  .gitignore
  package.json
  src/app.js
Labels: chore, security

#2 Security: Added security policy file
  SECURITY.md
Labels: chore, security

#3 Patch: Renamed Remote Git
  README.md
  package.json
Labels: chore, patch

#4 Chore: Added a development plant for the MVP Chatbot
  README.md
Labels: documentation, chore

#13 feature/post-request
  .env.example
  package.json
  src/app.js
  src/lib/post_request.js
Labels: feature

#23 feature: chat-history
  src/lib/chat_history.js
  src/lib/post_request.js
Labels: feature

#26 Feature: Enhance React Frontend with Chat Interface and Style Improvements
  src/frontend/.gitignore
  src/frontend/README.md
  src/frontend/package.json
  src/frontend/public/favicon.ico
  src/frontend/public/index.html
  src/frontend/public/logo192.png
  src/frontend/public/logo512.png
  src/frontend/public/manifest.json
  src/frontend/public/robots.txt
  src/frontend/src/App.css
  src/frontend/src/App.js
  src/frontend/src/App.test.js
  src/frontend/src/components/Chat.css
  src/frontend/src/components/Chat.js
  src/frontend/src/components/ChatInput.js
  src/frontend/src/components/Message.css
  src/frontend/src/components/Message.js
  src/frontend/src/index.css
  src/frontend/src/index.js
  src/frontend/src/logo.svg
  src/frontend/src/reportWebVitals.js
  src/frontend/src/setupTests.js
Labels: feature
